apiVersion: v1
kind: Service
metadata:
  name: argilla
  labels:
    app: argilla
spec:
  selector:
    app: morpheus-feedback-api
  ports:
    - protocol: TCP
      port: 6900
      targetPort: 6900
  type: ClusterIP
