apiVersion: apps/v1
kind: Deployment
metadata:
  name: morpheus-feedback-api
  labels:
    app: morpheus-feedback-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: morpheus-feedback-api
  template:
    metadata:
      labels:
        app: morpheus-feedback-api
    spec:
      containers:
        - name: flask-service
          image: your-registry/argilla-feedback-gateway:latest
          ports:
            - containerPort: 5001
          env:
            - name: ARGILLA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: argilla-secrets
                  key: api_key
            - name: ARGILLA_API_URL
              value: "http://localhost:6900"   # Internal Argilla endpoint
        - name: argilla-server
          image: argilla/argilla-server:latest
          ports:
            - containerPort: 6900
          env:
            - name: USERNAME
              value: argilla
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  key: argilla_password
                  name: argilla-secrets
          envFrom:
            - configMapRef:
                name: argilla-config
        - name: argilla-worker
          image: argilla/argilla-worker:latest
          command: ["bash","-c","python -m argilla_server worker --num-workers $BACKGROUND_NUM_WORKERS"]
          envFrom:
            - configMapRef:
                name: argilla-config
          env:
            - name: BACKGROUND_NUM_WORKERS
              value: "2"
        - name: redis
          image: redis:6
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
          env:
            - name: node.name
              value: "elasticsearch"

            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"

            - name: discovery.type
              value: "single-node"

            - name: cluster.name
              value: "es-argilla-local"

            - name: cluster.routing.allocation.disk.threshold_enabled
              value: "false"

            - name: xpack.security.enabled
              value: "false"


        - name: postgresql
          image: postgres:13
          env:
            - name: POSTGRES_USER
              value: "argilla"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: argilla-secrets
                  key: postgres_password
            - name: POSTGRES_DB
              value: "argilla_db"
