apiVersion: v1
kind: Service
metadata:
  name: morpheus-feedback-api
  labels:
    app: morpheus-feedback-api
spec:
  selector:
    app: morpheus-feedback-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
